server.port: 9091

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.60.138:8848
        group: SEATA_GROUP
  application.name: order-service
  datasource.url: jdbc:mysql://localhost:3306/db_order?allowMultiQueries=true
  datasource.driverClassName: com.mysql.jdbc.Driver
  datasource.username: root
  datasource.password: 123456


  main:
    allow-circular-references: true
seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    # 参考tc服务自己的registry.conf中的配置
    type: nacos
    nacos: # tc
      server-addr: 192.168.60.138:8848
      namespace: ""
      group: SEATA_GROUP
      application: seata-server # tc服务在nacos中的服务名称
      cluster: default
  service:
    vgroup-mapping: # 事务组与TC服务cluster的映射关系
      order-service-seata-service-group: default
